repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: pylint
  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.11.1  # Use the ref you want to point at
    hooks:
    -   id: pylint
